from optithms.algoritmos.univariable.acotamiento import BusquedaExhaustiva
from optithms.algoritmos.univariable.acotamiento import FaseDeAcotamiento
from optithms.algoritmos.univariable.eliminacion_regiones import IntervalosMitad
from optithms.algoritmos.univariable.eliminacion_regiones import Fibonacci
from optithms.algoritmos.univariable.eliminacion_regiones import BusquedaDorada
from optithms.algoritmos.univariable.gradiente import NewtonRaphson