from optithms.algoritmos.univariable.acotamiento import BusquedaExhaustiva
from optithms.algoritmos.univariable.acotamiento import FaseDeAcotamiento
from optithms.algoritmos.univariable.eliminacion_regiones import IntervalosMitad